project:
  type: website
  output-dir: docs

website:
  title: "Austin Kennedy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



