project:
  type: website
  output-dir: docs

website:
  title: "Austin Kennedy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: images/CV_AustinKennedy.pdf
        text: CV

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



