project:
  type: website
  output-dir: docs

website:
  title: "Austin Kennedy"
  favicon: images/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: images/CV_AustinKennedy.pdf
        text: CV
        
    right:
      - icon: envelope
        href: mailto:auke9230@colorado.edu
      - icon: github
        href: https://github.com/austinkennedy


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    tags:
    - Austin Kennedy
    - Github Pages
    - Economics
    - PhD Candidate
    - PhD Economics
    - Econometrics
    - Applied Microeconomics
    - Applied Econometrics
    - Applied Microeconometrics
    - Causal Inference
    - Causal ML
    - Causal Machine Learning
    - Academic
    - Economist
    - Economist Intern
    - Amazon
    - Data Science
    - Cryptocurrency
    - FDI
    - University of Colorado
    - CU
    - CU Boulder
    - Google



